version: '3.8'

services:
  web:
    build: .
    container_name: real_estate_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://your_db_user:your_db_password@db/your_db_name
    volumes:
      - .:/app
    networks:
      - real_estate_net

  db:
    image: postgres:14
    container_name: real_estate_db
    restart: always
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - real_estate_net

volumes:
  postgres_data:

networks:
  real_estate_net:
